# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='cb.proto',
  package='cygnus',
  serialized_pb='\n\x08\x63\x62.proto\x12\x06\x63ygnus\"\xbb\x01\n\x04Term\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\'\n\x08locality\x18\x02 \x02(\x0e\x32\x15.cygnus.Term.Locality\x12\x10\n\x08location\x18\x03 \x02(\r\x12\x0e\n\x06schema\x18\x04 \x02(\r\x12\x0e\n\x06offset\x18\x05 \x01(\r\x12\x0e\n\x06length\x18\x06 \x01(\r\":\n\x08Locality\x12\x05\n\x01R\x10\x00\x12\x06\n\x02\x43\x46\x10\x01\x12\x06\n\x02\x43Q\x10\x02\x12\x06\n\x02\x43V\x10\x03\x12\x06\n\x02TS\x10\x04\x12\x07\n\x03VAL\x10\x05\"6\n\x06Schema\x12\x10\n\x08termType\x18\x01 \x02(\t\x12\x1a\n\x04term\x18\x02 \x03(\x0b\x32\x0c.cygnus.Term')



_TERM_LOCALITY = descriptor.EnumDescriptor(
  name='Locality',
  full_name='cygnus.Term.Locality',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='R', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CF', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CQ', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CV', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TS', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VAL', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=150,
  serialized_end=208,
)


_TERM = descriptor.Descriptor(
  name='Term',
  full_name='cygnus.Term',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='cygnus.Term.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='locality', full_name='cygnus.Term.locality', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='location', full_name='cygnus.Term.location', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='schema', full_name='cygnus.Term.schema', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='cygnus.Term.offset', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='length', full_name='cygnus.Term.length', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TERM_LOCALITY,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=208,
)


_SCHEMA = descriptor.Descriptor(
  name='Schema',
  full_name='cygnus.Schema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='termType', full_name='cygnus.Schema.termType', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='term', full_name='cygnus.Schema.term', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=210,
  serialized_end=264,
)

_TERM.fields_by_name['locality'].enum_type = _TERM_LOCALITY
_TERM_LOCALITY.containing_type = _TERM;
_SCHEMA.fields_by_name['term'].message_type = _TERM
DESCRIPTOR.message_types_by_name['Term'] = _TERM
DESCRIPTOR.message_types_by_name['Schema'] = _SCHEMA

class Term(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TERM
  
  # @@protoc_insertion_point(class_scope:cygnus.Term)

class Schema(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCHEMA
  
  # @@protoc_insertion_point(class_scope:cygnus.Schema)

# @@protoc_insertion_point(module_scope)
